### ISSUE TITLE
Add Japanese language translation to README.md

### ISSUE THREAD

**Issue by biskwikman** [biskwikman/jpn-atlas#1]
I would like to have the README.md file in Japanese as well as English, since this is Japanese data. I will get around to it, but my Japanese ability is not that great, and it will end up sounding strange or confusing. If someone is with a higher level of Japanese language ability is interested in this please leave a comment!

**Comment by biskwikman** [comment]
I've translated the REAME.md file, but I'm sure it could be improved. Anyone who thinks they can make it more clear feel free to do so.

**Comment by sugi2000** [comment]
I recommend that you change the description of this project as follows.

> TopoJSONフォーマットの日本の国、都道府県、市区町村の境界データ。

**Comment by biskwikman** [comment]
Thanks! I've changed it.
